[package]
name = "bigdecimal"
version = "0.3.1+dev"
authors = ["Andrew Kubera"]
description = "Arbitrary precision decimal numbers"
documentation = "https://docs.rs/bigdecimal"
homepage = "https://github.com/akubera/bigdecimal-rs"
repository = "https://github.com/akubera/bigdecimal-rs"
keywords = ["mathematics", "numerics", "decimal", "arbitrary-precision", "floating-point"]
license = "MIT/Apache-2.0"

[dependencies]
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
serde = { version = "1.0", optional = true }

[dev-dependencies]
lazy_static = "1.4"
paste = "1.0"

[dev-dependencies.serde_json]
version = "1.0"

[build-dependencies]
autocfg = "1"

[features]
string-only = []
