[package]
name = "bigdecimal"
version = "0.4.0+dev"
authors = ["Andrew Kubera"]
description = "Arbitrary precision decimal numbers"
documentation = "https://docs.rs/bigdecimal"
homepage = "https://github.com/akubera/bigdecimal-rs"
repository = "https://github.com/akubera/bigdecimal-rs"
keywords = [
    "mathematics",
    "numerics",
    "decimal",
    "arbitrary-precision",
    "floating-point",
    "no-std",
]
license = "MIT/Apache-2.0"

[dependencies]
libm = "0.2.6"
num-bigint = { version = "0.4", default-features = false }
num-integer = { version = "0.1", default-features = false }
num-traits = { version = "0.2", default-features = false }
serde = { version = "1.0", optional = true, default-features = false }

[dev-dependencies]
serde_json = "1.0"
siphasher = { version = "0.3.10", default-features = false }

[features]
default = ["std"]
alloc = []
string-only = []
std = ["num-bigint/std", "num-integer/std", "num-traits/std", "serde/std"]
